// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(LigaContext))]
    partial class LigaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Models.Domacin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("EkipaDomacinID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EkipaDomacinID");

                    b.ToTable("Domacin");
                });

            modelBuilder.Entity("Models.Ekipa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Bodovi")
                        .HasColumnType("int");

                    b.Property<int?>("EkipaStadionID")
                        .HasColumnType("int");

                    b.Property<string>("ImeEkipe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("putanjaSlike")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EkipaStadionID");

                    b.ToTable("Ekipe");
                });

            modelBuilder.Entity("Models.Gost", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("EkipaGostID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EkipaGostID");

                    b.ToTable("Gost");
                });

            modelBuilder.Entity("Models.Igrac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("BrojNaDresu")
                        .HasColumnType("int");

                    b.Property<int?>("IgracEkipeID")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pozicija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("IgracEkipeID");

                    b.ToTable("Igraci");
                });

            modelBuilder.Entity("Models.Kolo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("krajkKola")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("pocetakKola")
                        .HasColumnType("datetime2");

                    b.Property<int>("rbrKola")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Kola");
                });

            modelBuilder.Entity("Models.Stadion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("StadionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Stadioni");
                });

            modelBuilder.Entity("Models.Strelac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("StrelacIgracID")
                        .HasColumnType("int");

                    b.Property<int?>("StrelacUtakmiceID")
                        .HasColumnType("int");

                    b.Property<int>("minutGola")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StrelacIgracID");

                    b.HasIndex("StrelacUtakmiceID");

                    b.ToTable("Strelci");
                });

            modelBuilder.Entity("Models.Utakmica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DatumIVremeUtakmice")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DomacaEkipaID")
                        .HasColumnType("int");

                    b.Property<int?>("GostujucaEkipaID")
                        .HasColumnType("int");

                    b.Property<int>("Pobednik")
                        .HasColumnType("int");

                    b.Property<int?>("UtakmicaKoloID")
                        .HasColumnType("int");

                    b.Property<int>("brGolovaDomacin")
                        .HasColumnType("int");

                    b.Property<int>("brGolovaGost")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DomacaEkipaID");

                    b.HasIndex("GostujucaEkipaID");

                    b.HasIndex("UtakmicaKoloID");

                    b.ToTable("Utakmice");
                });

            modelBuilder.Entity("Models.Domacin", b =>
                {
                    b.HasOne("Models.Ekipa", "EkipaDomacin")
                        .WithMany("EkipaDomacin")
                        .HasForeignKey("EkipaDomacinID");

                    b.Navigation("EkipaDomacin");
                });

            modelBuilder.Entity("Models.Ekipa", b =>
                {
                    b.HasOne("Models.Stadion", "EkipaStadion")
                        .WithMany("StadionEkipa")
                        .HasForeignKey("EkipaStadionID");

                    b.Navigation("EkipaStadion");
                });

            modelBuilder.Entity("Models.Gost", b =>
                {
                    b.HasOne("Models.Ekipa", "EkipaGost")
                        .WithMany("EkipaGost")
                        .HasForeignKey("EkipaGostID");

                    b.Navigation("EkipaGost");
                });

            modelBuilder.Entity("Models.Igrac", b =>
                {
                    b.HasOne("Models.Ekipa", "IgracEkipe")
                        .WithMany("ListaIgraca")
                        .HasForeignKey("IgracEkipeID");

                    b.Navigation("IgracEkipe");
                });

            modelBuilder.Entity("Models.Strelac", b =>
                {
                    b.HasOne("Models.Igrac", "StrelacIgrac")
                        .WithMany("IgracStrelc")
                        .HasForeignKey("StrelacIgracID");

                    b.HasOne("Models.Utakmica", "StrelacUtakmice")
                        .WithMany("UtakmicaStrelci")
                        .HasForeignKey("StrelacUtakmiceID");

                    b.Navigation("StrelacIgrac");

                    b.Navigation("StrelacUtakmice");
                });

            modelBuilder.Entity("Models.Utakmica", b =>
                {
                    b.HasOne("Models.Domacin", "DomacaEkipa")
                        .WithMany()
                        .HasForeignKey("DomacaEkipaID");

                    b.HasOne("Models.Gost", "GostujucaEkipa")
                        .WithMany()
                        .HasForeignKey("GostujucaEkipaID");

                    b.HasOne("Models.Kolo", "UtakmicaKolo")
                        .WithMany("KoloUtakmice")
                        .HasForeignKey("UtakmicaKoloID");

                    b.Navigation("DomacaEkipa");

                    b.Navigation("GostujucaEkipa");

                    b.Navigation("UtakmicaKolo");
                });

            modelBuilder.Entity("Models.Ekipa", b =>
                {
                    b.Navigation("EkipaDomacin");

                    b.Navigation("EkipaGost");

                    b.Navigation("ListaIgraca");
                });

            modelBuilder.Entity("Models.Igrac", b =>
                {
                    b.Navigation("IgracStrelc");
                });

            modelBuilder.Entity("Models.Kolo", b =>
                {
                    b.Navigation("KoloUtakmice");
                });

            modelBuilder.Entity("Models.Stadion", b =>
                {
                    b.Navigation("StadionEkipa");
                });

            modelBuilder.Entity("Models.Utakmica", b =>
                {
                    b.Navigation("UtakmicaStrelci");
                });
#pragma warning restore 612, 618
        }
    }
}
